// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muwnrovggwedvckszbfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11d25yb3ZnZ3dlZHZja3N6YmZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzM2NDEsImV4cCI6MjA3Mzc0OTY0MX0.9pS1qFeh5le4rRnOsEBisj3Z_S_n0ROICQOiiKPXvig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});